# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date_of_test', models.DateTimeField()),
                ('max_marks', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_id',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='classroom.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='answer1',
            field=models.CharField(default=' ', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='answer2',
            field=models.CharField(default=' ', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='answer3',
            field=models.CharField(default=' ', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='answer4',
            field=models.CharField(default=' ', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answers',
            name='isCorrect',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
        migrations.AddField(
            model_name='test',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Course'),
        ),
        migrations.AddField(
            model_name='questions',
            name='test_id',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='classroom.Test'),
            preserve_default=False,
        ),
    ]
