# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20160505_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
